before_script:
  - . ~/.nvm/nvm.sh && nvm use 6

stages:
  - test

test:
  stage: test
  tags:
    - shell
    - online.net
    - mongo
    - elasticsearch
    - redis
  script:
   - npm i
   - grunt
