
stages:
  - linters
  - tests

.test-template: &test-template
  image: node:10-stretch
  tags:
    - docker
  before_script:
    - npm install -g grunt-cli
    - npm i

linters:
  <<: *test-template
  stage: linters
  script:
    - grunt -v linters
  except:
    variables:
      - $SKIP_LINTERS

test-unit-backend:
  <<: *test-template
  stage: tests
  script:
    - grunt -v test-unit-backend
  except:
    variables:
      - $SKIP_TESTS
